version: 2

sources:
  - name: raw
    database: iceberg
    schema: curated
    tables:
      - name: temperature
      - name: humidity
      - name: vibration
      - name: evse_electrical
      - name: evse_state
      - name: evse_session_event
