name: 'ev_dbt'
version: '1.0.0'
profile: 'ev_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ev_dbt:  
    +on_schema_change: sync_all_columns

    staging:
      +materialized: view

    marts:
      +materialized: table
 